packages:
  - packages/**

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@biomejs/biome': ^2.3.4
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.29.7
    '@eslint/core': ^0.17.0
    '@types/node': ^24.10.0
    '@virtual-live-lab/eslint-config': ^2.3.1
    '@virtual-live-lab/tsconfig': ^2.1.21
    eslint: ^9.39.1
    eslint-plugin-react: ^7.37.5
    fs-fixture: ^2.10.1
    globals: ^16.5.0
    pkg-pr-new: ^0.0.60
    publint: ^0.3.15
    tsdown: ^0.16.1
    typescript: ^5.9.3
    unplugin-unused: ^0.5.6
    vitest: ^4.0.8
  prod:
    "@typescript-eslint/utils": ^8.46.4
    empathic: ^2.0.0
    gunshi: ^0.27.0-alpha.8
    mlly: ^1.8.0
    pathe: ^2.0.3
    unrun: ^0.2.26
    typescript-eslint: ^8.46.4

onlyBuiltDependencies:
  - esbuild
