packages:
  - packages/**

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@biomejs/biome': ^2.3.13
    '@changesets/changelog-github': ^0.5.2
    '@changesets/cli': ^2.29.8
    '@eslint/core': ^1.1.0
    '@types/node': ^24.10.0
    '@virtual-live-lab/eslint-config': ^2.3.1
    '@virtual-live-lab/tsconfig': ^2.1.21
    eslint: ^9.39.2
    eslint-plugin-react: ^7.37.5
    fs-fixture: ^2.11.0
    globals: ^17.3.0
    pkg-pr-new: ^0.0.62
    publint: ^0.3.17
    tsdown: ^0.20.1
    typescript: ^5.9.3
    unplugin-unused: ^0.5.7
    vitest: ^4.0.18
  prod:
    '@typescript-eslint/utils': ^8.54.0
    empathic: ^2.0.0
    gunshi: ^0.27.5
    mlly: ^1.8.0
    pathe: ^2.0.3
    typescript-eslint: ^8.54.0
    unrun: ^0.2.26

onlyBuiltDependencies:
  - esbuild
