packages:
  - packages/**

catalogs:
  biome:
    '@biomejs/biome': 2.3.4
  build:
    '@arethetypeswrong/cli': 0.18.2
    publint: 0.3.12
    tsdown: 0.13.0
    unplugin-unused: 0.5.1
  eslint:
    '@virtual-live-lab/eslint-config': 2.3.1
    eslint: 9.39.1
    typescript-eslint: 8.46.3
  test:
    fs-fixture: 2.8.1
    vitest: 4.0.8
  typescript:
    '@virtual-live-lab/tsconfig': 2.1.21
    typescript: 5.9.3

onlyBuiltDependencies:
  - esbuild
